### ISSUE TITLE
Problém s načítáním dat košíku přes ajax

### ISSUE THREAD

**Issue by ladzo** [shoptet/templates-assets#1]
v souboru assets\00\js\libs\cart.js
problém na řádku 81  var cartContent = $.parseJSON(response).payload;
parseJSON vrátí chybu Uncaught SyntaxError: Unexpected token o in JSON at position 1

**Comment by VencaV** [comment]
Thank you for the report, fixed with commit https://github.com/Shoptet/templates-assets/commit/82625e0122a309daf62ca6f6664f6d79d9a77ed9. Now you have to rebuild your JS/CSS from updated assets.
